Sources/MG-SHOPPING/MG-SHOPPING/Controllers/CartController.cs
using MG_Model.CodeHandle.Assets;
using MG_Model.CodeHandle.CartCustomerModel;
using MG_Model.CodeHandle.CustomerManagerFolder;
using MG_Model.CodeHandle.UserModel;
using MG_Model.EF;
using MG_SHOPPING.Models.Detail;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MG_SHOPPING.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/
        public ActionResult Index()
        {
            var u = (User)Session["LOGIN_KEY"];
            ViewBag.InforData = new Customer();
            if (u != null)
            {
                ViewBag.InforData = (Customer)Session["CUSTOMER"];
            }
            //if (u.GroupId.Equals("ADMIN")) return RedirectToAction("Index", "adminCart", new { area = "admin" });
            var model=(List<ModelCart>)Session["CART_ITEM"];
            return View(model);
        }
        
        public ActionResult deleteProduct(int id)
        {
            var list = (List<ModelCart>)Session["CART_ITEM"];
            foreach (var i in list)
            {
                if (i.id == id) { list.Remove(i); break; }
            }
            Session["CART_ITEM"] = list;
            return Content("SUCCESS");
        }
        [HttpPost]
        public ActionResult PostOrder(Customer model)
        {
            var user = (User)Session["LOGIN_KEY"];
            var p = new CustomersProvider().getbyusername(user.username).id;
            Session["CUSTOMER_BUOGHT"] = model;
            if (p > 0)
            {
                Cart cart;
                foreach (var i in (List<ModelCart>)Session["CART_ITEM"])
                {
                    cart = new Cart();
                    cart.CustomerID = p;
                    cart.ProductID = i.id;
                    cart.count = i.quarity;
                    cart.Price = i.price;
                    cart.dateBought = DateTime.Now;
                    cart.Status = false;
                    new CartCustomerProvider().Insert(cart);
                }
            }
            else { return Redirect("/xem-gio-hang"); }
            return Redirect("/xem-lai-hoa-don");
        }
        public ActionResult SaveCarts()
        { 
            
            var u=(User)Session["LOGIN_KEY"];
            if (u == null) return Redirect("/Dang-Nhap-or-Dang-Ki");
            if (u != null)
            { 
                var cp = new CustomersProvider().getbyusername(u.username); 
                Session["CUSTOMER"] = cp;
                var src = new CartCustomerProvider().getAll().Where(x => x.CustomerID == cp.id).ToList();//cart
                var des=(List<ModelCart> )Session["CART_ITEM"];//ModelCart
                processCart(ModelCart.converterx(src), des,false,cp.id);
            }
            return Redirect("/");
        }
        public void processCart(List<ModelCart> s,List<ModelCart> d,bool status,int cusid)
        {
            var provider = new CartCustomerProvider();
            foreach (var i in s)
            {
                var count = d.Where(x => x.id == i.id).Count();
                if (count == 0)
                { 
                    //delete
                    provider.Delete(i.id.ToString(),cusid.ToString());
                }
            }
            foreach (var i in d)
            {
                var count = s.Where(x => x.id == i.id).Count();
                if (count == 0)
                { 
                    //insert to database
                    provider.Insert(ModelCart.convert(i,status,cusid));
                }
                else if (count > 0)
                { 
                    //update to database
                    provider.Update(ModelCart.convert(i,status,cusid), i.id.ToString());
                }
            }
        }
       
    }
}

Sources/MG-SHOPPING/MG-SHOPPING/Controllers/MenuController.cs
using MG_Model.CodeHandle.Assets;
using MG_Model.CodeHandle.HomeModel;
using MG_Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MG_Model.CodeHandle.MenuCategoryFolder;
using MG_Model.CodeHandle.MenuManagerFolder;

namespace MG_SHOPPING.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Memu/

        [ChildActionOnly]
        public ActionResult _getBanner()
        {
            var _p = new PublicComponent()._getMenu(10);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getBrands()
        {
            var _p = new PublicComponent()._getMenu(11);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getMainMenu()
        {
            var _p = new PublicComponent()._getMenu().Where(x=>x.Submenu!=null||x.CategoryMenu==1).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getLeftMenu()
        {
            var _p = new PublicComponent()._getMenu(1).Where(x=>x.Submenu==2).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getPolicy()
        {
            var _p = new PublicComponent()._getMenu(3);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getRecommend()
        {
            ViewBag.Recommend = new PublicComponent().getRecommend(4);
            var _p = new MenuManagerProvider().getAll().Where(x => x.Submenu == 32).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getAbout()
        {
            var _p = new PublicComponent()._getMenu(4);
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getSale()
        {
            ViewBag.Sale = new Home().getListSale().ToArray();
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult _forType()
        {
            ViewBag.Type = new PublicComponent().getRecommend(8).ToArray();
            var _p = new MenuManagerProvider().getAll().Where(x => x.Submenu == 32).ToList();
            return PartialView(_p);
        }
        [ChildActionOnly]
        public ActionResult _getHot()
        {
            var p = new Home().getHot();
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _detailInfor()
        {
            var p = new PublicComponent()._getMenu(8);
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _getShared()
        {
            var p = new PublicComponent()._getMenu(5);
            return PartialView(p);
        }
        [ChildActionOnly]
        public ActionResult _Login()
        {
            var p = (User)Session["LOGIN_KEY"];
            return PartialView(p);
        }

    }
}

Sources/MG-SHOPPING/MG-SHOPPING/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IList<MG_SHOPPING.Models.Detail.ModelCart>
        @{Html.RenderAction("_getBanner", "Menu");}
		<!--phan session của main-->
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						@{Html.RenderAction("_getLeftMenu", "Menu");}
						<div class="brands_products"><!--brands_products-->
							<div class="brands-name">
								<div class="menu-container">
      
									  <div class="top_nav">
										<h2 class="text-center">Hàng Hiệu</h2>
									  </div>
								    @{Html.RenderAction("_getBrands", "Menu");}
								</div>
							</div>
						</div><!--/brands_products-->
						
						
					</div>	
				</div>
				
				<div class="col-sm-9 padding-right">
					<section id="cart_items">
						<h2 class="text-center"><span>GIỎ HÀNG</span></h2>
							<div class="table-responsive cart_info">
								<table class="table table-condensed">
									<thead>
										<tr class="cart_menu">
											<td class="image">Hình ảnh</td>
											<td class="description">Mô tả</td>
											<td class="price">Giá</td>
											<td class="quantity">Số lượng</td>
											<td class="total">Tổng Tiền</td>
											<td class="text-center">Clear</td>
										</tr>
									</thead>
									<tbody id="bodyblock">
									</tbody>
								</table>
                                <script src="~/Scripts/jquery-2.2.1.min.js"></script>
                                <script src="~/Scripts/_cartProcess.js"></script>
						</div>
					</section> <!--/#cart_items-->

					<section id="do_action">
                        <div class="col-sm-9">
                                <div class="heading">
								<h3 style="color:#A13091; font-weight:bold;">Những gì cần làm sau cùng để quá trình mua hàng được xác nhận.!!!</h3>
								<p>Vui lòng xem hóa đơn và điền thông tin để chúng tôi chuyển hàng tới bạn....</p>
							</div>
                        </div>
                        <button class="btn btn-info btn-lg" data-toggle="modal" data-target="#FORM_MUA">Mua</button>
						<button class="btn btn-warning btn-lg" onclick="location.href='/Cart/SaveCarts'">Lưu lại</button>	
							<div class="row">

								<div class="col-sm-12">
                                    <div class="col-sm-9">
                                        <div class="total_area">
												<h2 class="text-center"><strong>Thông tin đơn hàng</strong></h2>
												<ul id="detaildata"></ul>
										        <button class="btn btn-default update"id="updatePage">Cập Nhật</button>
										</div>
                                    </div>
								</div>
                                
							</div>
					</section><!--/#do_action-->
				</div>	
				</div>
			</div>
		</section>

<div class="modal fade" id="FORM_MUA" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title"><span class="text-center">Thông tin khách hàng</span></h2>
        </div>
          <form style="padding-left:10px;" onsubmit="return _cartbill()" action="/Cart/PostOrder" method="post">
        <div class="modal-body">
									<div class="chose_area">
											  <div class="form-group">
												<label>Tên Bạn:</label>
												<input type="text" class="form-control" name="nameCustomer" value="@ViewBag.InforData.nameCustomer" placeholder="Tên bạn">
											  </div>
											   <div class="form-group">
												<label>Tuổi:</label>
												<input type="text" class="form-control" name="age"  value="@ViewBag.InforData.age"  placeholder="Tuổi bạn">
											  </div>
											   <div class="form-group">
													<label>Bạn là:</label>
												<div class="single_field" >
													<select name="sex" >
														<option value="true" @(ViewBag.InforData.sex==true)?"selected":"" >Nam</option>
														<option value="false"   @(ViewBag.InforData.sex==false)?"selected":"">Nữ</option>
													</select>
												</div>
											  </div>
											   <div class="form-group">
												<label>Địa chỉ:</label>
												<input type="text" class="form-control" name="adress"  value="@ViewBag.InforData.adress" placeholder="Địa chỉ">
											  </div>
											   <div class="form-group">
												<label>Số điện thoại:</label>
												<input type="text" class="form-control" name="phoneNumber" value="@ViewBag.InforData.phoneNumber" placeholder="Số điện thoại">
											  </div>
											  <div class="form-group">
												<label>Email:</label>
												<input type="email" class="form-control" name="Email" value="@ViewBag.InforData.Email" placeholder="Email">
											  </div>
                                            <div class="form-group">
												<label>Fax:</label>
												<input type="text" class="form-control" name="Fax" value="@ViewBag.InforData.Fax" placeholder="FAX">
											  </div>
									</div>
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-defaul update" value="Submit">
		    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
        </div>
          </form>
      </div>
    </div>
    </div>					